const data = {
  shortDescription: `An enthusiastic Full Stack web developer Experienced in Javascript, React Js, NodeJs, MongoDB, Mysql, React Bootstrap, Tailwind CSS, MUI`,
  aboutme: [
    `I am doing Honours on Economics in Dhaka College. My passion is to learn 
    technology so I am doing MERN Stack Web Development with my academic career. As the 
    position is a Web Developer role my keen attention to design and developing knowledge 
    will be an added advantage for me to serve you with a quality-oriented service. I
    completed a complete MERN Stack Web Development course in`,
    ["programming hero", "https://web.programming-hero.com"],
    `Like I said, my passion is to learn new technology. I am implementing various packages 
    and tools after completing that course. Still now I am learning because I believe that 
    learning has no end. I have that ability to learn new technology within a short time if 
    I face something that is new for me. I have that quality to stick to something until I
    finish it and I feel good to do this. That's how I solve various problems and increase
    my knowledge.`,
  ],

  projects: [
    {
      name: "cycle mart",
      title: "Full Stack E-commerce App",
      technology: [
        "React",
        "Javascript",
        "Tailwind",
        "Node JS",
        "Express JS",
        "MongoDB",
      ],
      codeF: "https://github.com/iqbalhossen0483/cyclemart",
      codeB: "https://github.com/iqbalhossen0483/myserver",
      demo: "https://cycle-mart-3ff64.web.app/",
      img: "./cycle-mart.png",
      userName: "admin@admin.com",
      password: "AdminAdmin",
    },
    {
      name: "It valley",
      title: "Full Stack Online Shop",
      technology: [
        "Next JS",
        "Javascript",
        "Typescript",
        "MUI",
        "Node JS",
        "MongoDB",
      ],
      codeF: "https://github.com/iqbalhossen0483/it-vallely",
      demo: "https://it-vallely.vercel.app/",
      img: "./it-valley.png",
    },
    {
      name: "MTVnews",
      title: "Full Stack Online News",
      technology: ["Next js", "Tailwind", "Javascript", "Node JS", "Mysql"],
      codeF: "https://github.com/iqbalhossen0483/navieasoftnews2022",
      demo: "http://mtvnews24.com/",
      img: "./mtvnews.png",
      userName: "admin@gmail.com",
      password: "1234567",
    },
    {
      name: "Medicine Lagbe",
      title: "Online Stock Management Sogtoware",
      technology: ["Next js", "Tailwind", "Javascript", "Node JS", "Mysql"],
      codeF: "https://github.com/iqbalhossen0483/ecommerce",
      demo: "http://medicinelagbe.com/admin",
      img: "./medicine.png",
      userName: "admin@gmail.com",
      password: "123456",
    },
    {
      name: "Islamia Hospital",
      title: "Full Stack Hospital App",
      technology: ["React", "Javascript", "Node JS", "Express JS", "MongoDB"],
      codeF: "https://github.com/iqbalhossen0483/hospital",
      codeB: "https://github.com/iqbalhossen0483/myserver",
      demo: "https://islamia-hospital.web.app/",
      img: "./hospital.png",
      userName: "admin@admin.com",
      password: "AdminAdmin",
    },

    {
      name: "Ecostay",
      title: "Full Stack Apartment Sale App",
      technology: [
        "React",
        "Tailwind",
        "Typescript",
        "Javascript",
        "Node JS",
        "Express JS",
        "MongoDB",
      ],
      codeF: "https://github.com/iqbalhossen0483/apartment",
      codeB: "https://github.com/iqbalhossen0483/myserver",
      demo: "https://apartment-29968.web.app/",
      img: "./apartment.png",
    },

    {
      name: "Fooddy",
      title: "Full Stack Food Delivary App",
      technology: [
        "React",
        "Tailwind",
        "Typescript",
        "Javascript",
        "Node JS",
        "Express JS",
        "MongoDB",
      ],
      codeF: "https://github.com/iqbalhossen0483/food-delivery",
      codeB: "https://github.com/iqbalhossen0483/myserver",
      demo: "https://delivery-53abd.web.app/",
      img: "./food.png",
    },
    {
      name: "Tourism",
      title: "Full Stack tour App",
      technology: ["React", "Javascript", "Node JS", "Express JS", "MongoDB"],
      codeF: "https://github.com/iqbalhossen0483/tourism",
      codeB: "https://github.com/iqbalhossen0483/myserver",
      demo: "https://tourism-web-e4f05.web.app/",
      img: "./tourism.png",
    },
    {
      name: "Honda cdr",
      title: "Fronted",
      technology: ["HTML", "CSS", "Bootstrap"],
      codeF: "https://github.com/iqbalhossen0483/honda-cdr",
      demo: "https://honda-cdr.netlify.app/",
      img: "./honda-cdr.png",
    },
    {
      name: "Salary App",
      title: "Fronted",
      technology: ["HTML", "CSS", "Javascript"],
      codeF: "https://github.com/iqbalhossen0483/salary-app",
      demo: "https://salary-app83.netlify.app/",
      img: "./salary-app.png",
    },
    {
      name: "Calculator",
      title: "Fronted",
      technology: ["HTML", "CSS", "Javascript"],
      codeF: "https://github.com/iqbalhossen0483/calculator",
      demo: "https://calculator83.netlify.app/",
      img: "./calculator.png",
    },
    {
      name: "Player",
      title: "Fronted",
      technology: ["HTML", "CSS"],
      codeF: "https://github.com/iqbalhossen0483/player-html-css",
      demo: "https://player83.netlify.app/",
      img: "./player.png",
    },
    {
      name: "Baper Bank",
      title: "Fronted",
      technology: ["HTML", "Tailwind CSS", "Javascript"],
      codeF: "https://github.com/iqbalhossen0483/bank",
      demo: "https://bank83.netlify.app/",
      img: "./bank.png",
    },
    {
      name: "Pin Matcher",
      title: "Fronted",
      technology: ["HTML", "CSS", "Javascript"],
      codeF: "https://github.com/iqbalhossen0483/pin-matcher",
      demo: "https://pin-matcher83.netlify.app/",
      img: "./pin-matcher.png",
    },
  ],
  skills: [
    { name: "HTML", logo: "./skills/html.webp", lavel: "Excellent" },
    { name: "CSS", logo: "./skills/css.webp", lavel: "Excellent" },
    { name: "Tailwind", logo: "./skills/tailwind.webp", lavel: "Excellent" },
    { name: "MUI", logo: "./skills/mui.png", lavel: "Good" },
    { name: "Bootstrap", logo: "./skills/bootstrap.webp", lavel: "Good" },
    { name: "SASS", logo: "./skills/sass.webp", lavel: "Comfortable" },
    { name: "JS", logo: "./skills/js.webp", lavel: "Excellent" },
    { name: "Typescript", logo: "./skills/typescript.webp", lavel: "Good" },
    { name: "React", logo: "./skills/react.webp", lavel: "Excellent" },
    { name: "Next", logo: "./skills/next.webp", lavel: "Excellent" },
    { name: "Node", logo: "./skills/node.webp", lavel: "Good" },
    { name: "Express", logo: "./skills/express.webp", lavel: "Excellent" },
    { name: "MongoDB", logo: "./skills/mongodb.webp", lavel: "Excellent" },
    { name: "Mongoose", logo: "./skills/mongoose.png", lavel: "Good" },
    { name: "Mysql", logo: "./skills/mysql.png", lavel: "Excellent" },
    { name: "JWT", logo: "./skills/jwt.png", lavel: "Comfortable" },
    {
      name: "React Testing",
      logo: "./skills/react-testing.jpg",
      lavel: "Comfortable",
    },
    { name: "Firebase", logo: "./skills/firebase.webp", lavel: "Good" },
    { name: "Git", logo: "./skills/git.webp", lavel: "Comfortable" },
    { name: "Figma", logo: "./skills/figma.png", lavel: "Good" },
  ],
};

export default data;
